font_family                DM Mono
font_size                  14.0
# adjust_line_height         10
window_padding_width       5.0
macos_titlebar_color       background
macos_option_as_alt        left
macos_thicken_font         0.3

macos_custom_beam_cursor   yes
wheel_scroll_multiplier    3.0
allow_remote_control       yes
macos_show_window_title_in window
tab_bar_style              powerline
tab_powerline_style        slanted

map f1 set_colors ~/.config/kitty/tomorrow-night-bright.conf
map f2 set_colors ~/.config/kitty/piatto-light.conf

# iTerm2 like clearing behavior
# via https://github.com/kovidgoyal/kitty/issues/747#issuecomment-609143607
map cmd+k combine : clear_terminal scrollback active : send_text normal,application \x0c

# Cmd F Search behavior
# via https://github.com/kovidgoyal/kitty/issues/718#issuecomment-756800986
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# include piatto-light.conf
# include tomorrow.conf
include tomorrow-night.conf
